default_report:
	./vendor/bin/phpbench run benchmarks/JsonBench.php --report=default --output=html

aggregate_report:
	./vendor/bin/phpbench run benchmarks/JsonBench.php --report=aggregate --output=html